name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eval-x86_64:
    name: nix eval (x86_64-linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Evaluate package
        run: nix eval .#packages.x86_64-linux.default

  eval-aarch64:
    name: nix eval (aarch64-linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Evaluate package
        run: nix eval .#packages.aarch64-linux.default

  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run flake checks
        run: nix flake check --all-systems
